version: "3.8"

services:
  postgres:
    image: postgres:17.2

    container_name: epace-postgres
    environment:
      POSTGRES_DB: EPaCe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PS8289
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: epace-backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: EPaCe
      DB_USERNAME: postgres
      DB_PASSWORD: PS8289
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    container_name: epace-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8081/api
    depends_on:
      - backend

volumes:
  postgres_data:
